apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashprogram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashprogram
  template:
    metadata:
      labels:
        app: hashprogram
    spec:
      containers:
        - name: hashprogram
          image: hashprogram